services:
  # Frontend Angular
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge